### ISSUE TITLE
Importing krpc - name long is not defined (python 3.4.3)

### ISSUE THREAD

**Issue by seckujdivad** [krpc/krpc#330]
This is in the \krpc-0.3.5 directory. I get ImportError in other directories.

Code:
import krpc

Error report:
Traceback (most recent call last):
  File "C:\Users\[identity protection]\krpc-0.3.5\test.py", line 1, in <module>
    import krpc
  File "C:\Users\[identity protection]\krpc-0.3.5\krpc\__init__.py", line 3, in <module>
    from krpc.client import Client
  File "C:\Users\[identity protection]\krpc-0.3.5\krpc\client.py", line 4, in <module>
    from krpc.types import Types, DefaultArgument
  File "C:\Users\[identity protection]\krpc-0.3.5\krpc\types.py", line 31, in <module>
    PYTHON_VALUE_TYPES = [float, int, long, bool, str, bytes]
NameError: name 'long' is not defined

Before this I have done:
C:\Python34\Scripts\pip.exe install krpc
into a non-admin command line.

Windows 10 x64
Python 3.4.3

**Comment by djungelorm** [comment]
Works for me with Python 3 on both Windows and Linux.

Are you sure you are using the package installed by pip? From the error output it looks like you not, as the paths should mention `C:\Python34\Lib\site-packages`

(`long` is not a keyword in Python3, and is automatically patched when pip installs the package, so referencing the package files without installing via pip won't work)

**Comment by djungelorm** [comment]
I assume you resolved the issue?
