### ISSUE TITLE
Connect krpc fail

### ISSUE THREAD

**Issue by miswanting** [krpc/krpc#359]
I run this code in a thread named 'input'

> conn = krpc.connect(name='test')

Then get a error:

```
Exception in thread input:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\OneDrive\CODE\KSP-Pilot\dist\pilot.py", line 45, in inputStar
    self.do(cmd)
  File "D:\Users\OneDrive\CODE\KSP-Pilot\dist\pilot.py", line 56, in do
    conn = krpc.connect(name='test')
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\__init__.py", line 40, in connect
    return Client(rpc_connection, stream_connection)
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\client.py", line 36, in __init__
    setattr(self, snake_case(service.name), create_service(self, service))
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\service.py", line 189, in create_service
    cls._add_service_class_method(class_name, method_name, procedure)
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\service.py", line 307, in _add_service_class_method
    class_cls._add_method(name, func, doc=_parse_documentation(procedure.documentation))
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\service.py", line 134, in _parse_documentation
    doc = _parse_documentation_content(node).replace('\n', '')
  File "D:\Program Files\Anaconda3\lib\site-packages\krpc\service.py", line 118, in _parse_documentation_content
    return desc.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

version:

> ksp: 1.2.0.1586
> kRPC: 0.3.6-61-g0f6458a from #345 
> python: 3.5.2

**Comment by djungelorm** [comment]
You need to update your python client too with the version found here: https://krpc.s3.amazonaws.com/deploy/feature/ksp-1.2/714.1/client/krpc-python-0.3.6-61-g0f6458a.zip

**Comment by miswanting** [comment]
It worked. Thank you.
