### ISSUE TITLE
py client: Exception on import with protobuf 3.2.0

### ISSUE THREAD

**Issue by dtrauma** [krpc/krpc#378]
Importing krpc I get

```
Python 3.4.5 (default, Feb 20 2017, 07:40:20) 
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Code/Python/krpc/lib/python3.4/site-packages/krpc/__init__.py", line 2, in <module>
    from krpc.client import Client
  File "/home/user/Code/Python/krpc/lib/python3.4/site-packages/krpc/client.py", line 11, in <module>
    import krpc.schema.KRPC
  File "/home/user/Code/Python/krpc/lib/python3.4/site-packages/krpc/schema/KRPC.py", line 42, in <module>
    options=None),
  File "/home/user/Code/Python/krpc/lib/python3.4/site-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

```

using protobuf 3.2.0

**Comment by djungelorm** [comment]
Something broke backwards compatibility in 3.2.0.

Should work fine with 3.1.0.

**Comment by dtrauma** [comment]
Just tested, it does.

**Comment by dtrauma** [comment]
```
(krpc-venv) user@wrath ~/Code/Python/KerbalPie $ pip freeze|egrep krpc\|proto
krpc==0.3.8
protobuf==3.2.0
(krpc-venv) user@wrath ~/Code/Python/KerbalPie $ python
Python 3.4.5 (default, Feb 20 2017, 07:40:20) 
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Code/Python/krpc-venv/lib/python3.4/site-packages/krpc/__init__.py", line 2, in <module>
    from krpc.client import Client
  File "/home/user/Code/Python/krpc-venv/lib/python3.4/site-packages/krpc/client.py", line 11, in <module>
    import krpc.schema.KRPC
  File "/home/user/Code/Python/krpc-venv/lib/python3.4/site-packages/krpc/schema/KRPC.py", line 42, in <module>
    options=None),
  File "/home/user/Code/Python/krpc-venv/lib/python3.4/site-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
>>> 

```

**Comment by djungelorm** [comment]
Take a look this: https://github.com/krpc/krpc/issues/376#issuecomment-282589683

Might work around the issue, which i think is due to a bug with the protobuf 3.2.0 python library when an older protobuf C++ library is installed.

**Comment by dtrauma** [comment]
Yep, just tested this and got sidetracked, sorry, downgrading to PB 3.1.0 works again. System protobuf lib is 2.6.1 (/usr/lib64/libprotobuf.so.9.0.1).

**Comment by djungelorm** [comment]
Did some more digging and found that a change in protobuf v3.2.0 requires the generated code to be stored in a file named *_pb2.py (regardless of if it's protobuf v2 or v3). I'm putting together a v0.3.8.post1 release with this fix.
