### ISSUE TITLE
Can't install krpc with pip

### ISSUE THREAD

**Issue by OndrikB** [krpc/krpc#562]
When I try to install the krpc library with pip, it throws this error:

```
Collecting krpc
  Using cached https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip
    ERROR: Command errored out with exit status 1:
     command: 'd:\programy\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Temp\\pip-install-s4_i7ice\\krpc\\setup.py'"'"'; __file__='"'"'D:\\Temp\\pip-install-s4_i7ice\\krpc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'D:\Temp\pip-install-s4_i7ice\krpc\pip-egg-info'
         cwd: D:\Temp\pip-install-s4_i7ice\krpc\
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\programy\python\lib\site-packages\setuptools\__init__.py", line 18, in <module>
        import setuptools.version
      File "d:\programy\python\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "d:\programy\python\lib\site-packages\pkg_resources\__init__.py", line 80, in <module>
        from pkg_resources.extern import appdirs
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
      File "d:\programy\python\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
        __import__(extant)
      File "d:\programy\python\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
        import win32com.shell
    ValueError: source code string cannot contain null bytes
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any help?

**Comment by OndrikB** [comment]
To add to this, here's the command run again, in verbose mode
```
Created temporary directory: D:\Temp\pip-ephem-wheel-cache-g2hh227f
Created temporary directory: D:\Temp\pip-req-tracker-1m01zpl7
Created requirements tracker 'D:\\Temp\\pip-req-tracker-1m01zpl7'
Created temporary directory: D:\Temp\pip-install-bli3zvtb
1 location(s) to search for versions of krpc:
* https://pypi.org/simple/krpc/
Getting page https://pypi.org/simple/krpc/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/krpc/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/krpc/ HTTP/1.1" 304 0
Analyzing links from page https://pypi.org/simple/krpc/
  Found link https://files.pythonhosted.org/packages/d8/eb/7a8d02cd5d35750055f2445b1f8c2bed1bef48ef5054bfcc3a4e6090fafc/krpc-0.1.0.tar.gz#sha256=683c0da23a754692fab69701f1cfab796916cb1995400709a17a823e6a2fc87a (from https://pypi.org/simple/krpc/), version: 0.1.0
  Found link https://files.pythonhosted.org/packages/8a/44/48a0a3989bdbbd6c92c425614ac32c69d2c53c99ff3df12c83c23966bb82/krpc-0.1.0.zip#sha256=df5562874e92920714b788428966c5178b09700a8ecc7f002dbb5d5b4096ca99 (from https://pypi.org/simple/krpc/), version: 0.1.0
  Found link https://files.pythonhosted.org/packages/1d/2e/637b9949348394c3d0d1d2352ceb72ff64b5e0415158416c972e82bf49fc/krpc-0.1.1.tar.gz#sha256=afd8c002a63f5c29b8b28fbf4a97e5fdb066cf0d27566a00fb68092298bb8ba5 (from https://pypi.org/simple/krpc/), version: 0.1.1
  Found link https://files.pythonhosted.org/packages/15/09/ff97f0140c1d2e994cee324a0937892ed7e72ebb5487eaeaf69e82b5f323/krpc-0.1.1.zip#sha256=07cc6f0dbb4c25b6449334dbf0f7a66274827ed51c5212ad616255f372110eb5 (from https://pypi.org/simple/krpc/), version: 0.1.1
  Found link https://files.pythonhosted.org/packages/fc/b0/f817c23bab1b35d75b80c1202f22b666e01d5c37a6ef0378fdb58f9a3522/krpc-0.1.2.tar.gz#sha256=e7068a61dacf62e95f3c9f98dea92846863a93eb3a01c702e088a28a5193c840 (from https://pypi.org/simple/krpc/), version: 0.1.2
  Found link https://files.pythonhosted.org/packages/0f/78/a5358d7febb1ae2f7b10181b13b8d168b0ecec3b7f10c6ec6b9284f77a3d/krpc-0.1.2.zip#sha256=431cbad15286b938843c6adf1a45e055582758dd94948fb834b213d36c6c4eb7 (from https://pypi.org/simple/krpc/), version: 0.1.2
  Found link https://files.pythonhosted.org/packages/e5/77/74b9d52e64d85e9d6824e059a305cbe9f7fd45482c93f1a6c7619d1228f2/krpc-0.1.3.tar.gz#sha256=c8ed6fd6da903914a06bb261c4419d7631d9b9eba6fd05bd42460cef45d72ca5 (from https://pypi.org/simple/krpc/), version: 0.1.3
  Found link https://files.pythonhosted.org/packages/15/2b/a9a9d303e41dbc739c8aa1f1185550fa9b7e0350479dc63f5c63286a7854/krpc-0.1.3.zip#sha256=fc897dcbcb697bb40b414fc9a43e0f9753b9140e41d8a0c57f96d1383d922a04 (from https://pypi.org/simple/krpc/), version: 0.1.3
  Found link https://files.pythonhosted.org/packages/16/c6/93368efdf04ab6ea3b1fd5d32e6266cfd18b7aef99025367bf2384d1ebdb/krpc-0.1.4.tar.gz#sha256=5c378dd92d7cf64a447071c412ab08ac111c7804eb7928fa386aa8cee899dfa7 (from https://pypi.org/simple/krpc/), version: 0.1.4
  Found link https://files.pythonhosted.org/packages/4a/43/bfad51023ffc1c83bbc6b4fb02d8a44f2694d9f4bf3eaa2b31f5a0ba72e7/krpc-0.1.4.zip#sha256=bda03808b6b05d0babfa979d499ce118df31d4859341b0dc94476681808de2d9 (from https://pypi.org/simple/krpc/), version: 0.1.4
  Found link https://files.pythonhosted.org/packages/90/43/836010e48d61547815d979d00c2c5b24a15ac45f23331bb958e5d380c8f2/krpc-0.1.5.tar.gz#sha256=cb97d0f1ee51421a8be0e9f369fd6c020537ed5cdf68cdc688fc21040977866c (from https://pypi.org/simple/krpc/), version: 0.1.5
  Found link https://files.pythonhosted.org/packages/50/7d/e68e3639b66e68b0b01bae0634a5508b85274f74bbe0c5c38ab8a4c76e02/krpc-0.1.5.zip#sha256=7adc9e0df4a052c4c49eb3bce27b6617d909ef55256fec01530d82e8afd88285 (from https://pypi.org/simple/krpc/), version: 0.1.5
  Found link https://files.pythonhosted.org/packages/e0/d1/c9cb8d8992396164745f025889f008386705cbf7f11c30bed2605531ed28/krpc-0.1.6.tar.gz#sha256=69e0bcc765d96d175b5234ce9565f05463f868f4b1275226bf1d86e8f092a2a0 (from https://pypi.org/simple/krpc/), version: 0.1.6
  Found link https://files.pythonhosted.org/packages/54/89/a9833cf9cb4c7e0b4fead9f02b211fc977caa302e037e5b572cea42e52a1/krpc-0.1.6.zip#sha256=d29c8a0724093fab8dd1ec9e6b8d8f79dc1fc65204d540caa152b90223c7b92a (from https://pypi.org/simple/krpc/), version: 0.1.6
  Found link https://files.pythonhosted.org/packages/bf/88/a29322b0bcc5abfffce9e9ba734710f3eb0900f6779842fae065a06764ee/krpc-0.1.7.tar.gz#sha256=c7d8570c02bc92b9569ede3efc41e7ec9f958dd4933b5bfe804f164b563679e4 (from https://pypi.org/simple/krpc/), version: 0.1.7
  Found link https://files.pythonhosted.org/packages/9b/b1/7ecb8a4c24f9aee3eccf469afd1adf1eb8acc82eaf20a04d05945e085cc4/krpc-0.1.7.zip#sha256=d371151ad76baa5fe63d1979c7e456361db2625b474a5d213c3a3f7515023409 (from https://pypi.org/simple/krpc/), version: 0.1.7
  Found link https://files.pythonhosted.org/packages/6f/3e/ee0e0c93997ce3181a6b19b28850ac4cbea8f9588e3299df26bce32ec64c/krpc-0.1.8.tar.gz#sha256=dda1045e1b9ddaa34d30d499bd751713fd59148fc70e1ac3f5e6e33d22f8f00c (from https://pypi.org/simple/krpc/), version: 0.1.8
  Found link https://files.pythonhosted.org/packages/24/f2/5fb787b57cc60a00fe15c9c16cbf878ee7b3fe8809d9f8c114252c9c0edd/krpc-0.1.8.zip#sha256=7de6b422ea95cfee765aa16280f064577a9b81a7b5ea30b09737d233f295a5c2 (from https://pypi.org/simple/krpc/), version: 0.1.8
  Found link https://files.pythonhosted.org/packages/c1/b3/ab06aa529dbf68de2ad7c3507666e5c7fa3d54f9fac196ef0726bcd7bff1/krpc-0.1.9.tar.gz#sha256=198e9da14dd4e676585e15a32eb7e5164c0bbc9a829e1fcce227781147e8f41a (from https://pypi.org/simple/krpc/), version: 0.1.9
  Found link https://files.pythonhosted.org/packages/b5/67/17c5203863e30da05c784c35db218877941d6ba991ea63152ee35bfc1d35/krpc-0.1.9.zip#sha256=553b3d39f3ede46c0dbe05a54fb78cc23f4720ce967c3c22680cb3a1e2bdefe1 (from https://pypi.org/simple/krpc/), version: 0.1.9
  Found link https://files.pythonhosted.org/packages/b4/62/89d654897b7cc13d35645250f14c86bf103a6f535796b700f7e93960fced/krpc-0.1.10.tar.gz#sha256=6b9c61638c362637604bd645b8dc42c8addbe3074fc0f90a46732ad766f34e69 (from https://pypi.org/simple/krpc/), version: 0.1.10
  Found link https://files.pythonhosted.org/packages/a4/29/f3712db83a55648c3e80ba0a585b9a17714105d7c2845926ab6c01d22654/krpc-0.1.10.zip#sha256=dfb4fb4f8c7e0a6dbed32651bd478ca2c6ce66671516194e79282dbe16dd110e (from https://pypi.org/simple/krpc/), version: 0.1.10
  Found link https://files.pythonhosted.org/packages/ba/8f/a1e1596ec7527da7f897482dee90f48dc6cd43a2a3a79d71b263a4513aac/krpc-0.1.11.tar.gz#sha256=e317c28b9829cfac8ff75050640ba3ff732677f9ebaabca55eb3c59be160ecb4 (from https://pypi.org/simple/krpc/), version: 0.1.11
  Found link https://files.pythonhosted.org/packages/f3/19/37e0909d08425b8cfdff3fbef59040ea1917773573022af77732e50244d2/krpc-0.1.11.zip#sha256=e39a2fda9486185282faf6afdbb469949bdbddde10983aff64b1cf7527763ff1 (from https://pypi.org/simple/krpc/), version: 0.1.11
  Found link https://files.pythonhosted.org/packages/63/a7/216ca9458d8e57d23246aacdfb1a1dc556e741f3825a5993771d1cdba78b/krpc-0.1.12.tar.gz#sha256=9f649c7912e8525b411389928fc01a51bc73c3e1ebd39a09b680caca7663d754 (from https://pypi.org/simple/krpc/), version: 0.1.12
  Found link https://files.pythonhosted.org/packages/aa/8a/77b1ea1db128fe555ce11dc9461378ceed60931e68f47486a164e22bc0ea/krpc-0.1.12.zip#sha256=de0bf7e23df1489fa56fdfe4c7680bc9b3cb2e96b0f1695ee227813ac34e1132 (from https://pypi.org/simple/krpc/), version: 0.1.12
  Found link https://files.pythonhosted.org/packages/4a/f3/fb15eb4e84016cd8de50e14dde6b268aab630730bfb0230343a829f2e9f3/krpc-0.2.0.zip#sha256=a7c80bfbad866e1c39fb3e7a171be9f42d7015535475a420d4805f7e93d51582 (from https://pypi.org/simple/krpc/), version: 0.2.0
  Found link https://files.pythonhosted.org/packages/a1/50/27ddc04ab603dbcab19f08a76df2356c247b9cc94b0a5bd3d021d109548b/krpc-0.2.0.post1.zip#sha256=7923c478a13a4fa5ce441b4a65e9b9424fbc88a3d9887d14947d5b9cfa4d8c74 (from https://pypi.org/simple/krpc/), version: 0.2.0.post1
  Found link https://files.pythonhosted.org/packages/8c/fe/49f209da3fe79b09341d35f14232f83c53b11e229ac8d43c03e58c1e98f8/krpc-0.2.1.zip#sha256=542cdaa00e5736b3852905cb59da27f6f1dd2119cbfc5c3d38a0365f30e78ace (from https://pypi.org/simple/krpc/), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/06/38/98e34a39f77304e68d6b2a703694f62fe0687f028bf6134aa2ae3ded4aed/krpc-0.2.2.zip#sha256=3bb2eb29548c2026b3790b344fc235cb7bffe5335f73fb1837d4df93d24dd3ba (from https://pypi.org/simple/krpc/), version: 0.2.2
  Found link https://files.pythonhosted.org/packages/81/eb/01f80ca1b07ab1e4e8bb416f6a75d4ed4bb21b22aeca1d5d1f19a9698714/krpc-0.2.3.zip#sha256=ccbef05870a13398bb182b0fe4ce831e33b24a2fead27f7c5790196b7f80e37c (from https://pypi.org/simple/krpc/), version: 0.2.3
  Found link https://files.pythonhosted.org/packages/b0/30/84d162da0883e59a4e8b553c9faf0bca1056a4315c8a5ea1fdb5b469e72a/krpc-0.3.0.zip#sha256=7128c516be46c8539a049eaa7f69cde23dc8176da7edb1f983e78d528acd60d3 (from https://pypi.org/simple/krpc/), version: 0.3.0
  Found link https://files.pythonhosted.org/packages/8f/34/2dde89db156f69c4c0ffde3afccf642e07bcd9a317bcae26bb46cf3a4ee1/krpc-0.3.1.zip#sha256=c9c80e553a6acbcf853de0e0dfaec288caa4aa875b3ed85698e37f034dc3657c (from https://pypi.org/simple/krpc/), version: 0.3.1
  Found link https://files.pythonhosted.org/packages/7a/f5/a8bbdf9b6062d83577a1c5a51b2a8bff9685c0d3947463cfd81ef33c83c4/krpc-0.3.2.zip#sha256=26f3212dc58c4dce7356619272c2ab93706b64de9f48df965437c8a3468ab292 (from https://pypi.org/simple/krpc/), version: 0.3.2
  Found link https://files.pythonhosted.org/packages/2a/2e/6c2f75d3d6dc124ba46aaab4ad989a6bf9c05ffc7d72e13b5db473253b6e/krpc-0.3.3.zip#sha256=efdd30415ae024bb78d21f79560278907163edf61a997e9fc762205bac73d3d6 (from https://pypi.org/simple/krpc/), version: 0.3.3
  Found link https://files.pythonhosted.org/packages/67/4b/c422d306dbad3be264abd89499ed470a78d5022a77887ab36e7d645eed9a/krpc-0.3.4.zip#sha256=88bbf225c340dc8936facb2385abb21c423ef5902b35fdaac6cf1eadcfe4b686 (from https://pypi.org/simple/krpc/), version: 0.3.4
  Found link https://files.pythonhosted.org/packages/5a/32/384b36e6d983a0af26878b2f7e7292b2d4796f25caab2bf2cc3ce70942eb/krpc-0.3.5.zip#sha256=519ded24a71ec00527e5421bc430f27b30c620670060d8c1ed737db5d64aa7bf (from https://pypi.org/simple/krpc/), version: 0.3.5
  Found link https://files.pythonhosted.org/packages/22/c1/6b61a3909f4acdbdf89f0687c819abbf25314f6eb2b18e48653282dd8f45/krpc-0.3.6.zip#sha256=94f3cefd53ca535e7392210e86d7f9cd533de8a4f61999c5c7312bc8e015840b (from https://pypi.org/simple/krpc/), version: 0.3.6
  Found link https://files.pythonhosted.org/packages/fb/81/c732490c1b428bcc22ef0f7b989b86752ffa338da18cc76591d9fdc993e2/krpc-0.3.7.zip#sha256=0722f8ed41870937e76cfd64761cb67fe0c431231d9c7df916e7ebb184ddf1af (from https://pypi.org/simple/krpc/), version: 0.3.7
  Found link https://files.pythonhosted.org/packages/80/20/99a4a7cba2c4ac769fae3ede9b0fc95738419efbc4cc66252cb2e593df51/krpc-0.3.8.zip#sha256=0063d94c25db486d7ad97b1daadc55b9e68ca89b42141ba4b55404084456edb6 (from https://pypi.org/simple/krpc/), version: 0.3.8
  Found link https://files.pythonhosted.org/packages/6a/07/5447aa967386a2662478135a755fecea311df4f3ed377aa939c2ed34f478/krpc-0.3.8.post1.zip#sha256=fd56d3d0861264b2e848cd6515050b898325e3eab577a04644490e2547fd2562 (from https://pypi.org/simple/krpc/), version: 0.3.8.post1
  Found link https://files.pythonhosted.org/packages/d3/b6/a658bca73aae9f402adca249716416d06e0130c5a257dfb522a8c56c24dc/krpc-0.3.9.zip#sha256=3abfbcc097eeed764fa81a4928f658e6c232bca3cc7564224c4bfcee12be462c (from https://pypi.org/simple/krpc/), version: 0.3.9
  Found link https://files.pythonhosted.org/packages/78/ee/20146b05301b7528fa611cafc9f22340c27475603c9500bed3b366966ac1/krpc-0.3.9.post1.zip#sha256=8438ad1511f8ecb4b5b3263da1f529fa830458044fe7053bcd985a0ccdc01998 (from https://pypi.org/simple/krpc/), version: 0.3.9.post1
  Found link https://files.pythonhosted.org/packages/68/9b/cf50e779be7b735b0749798cb70479ea19941ed1548b6863778ce2d0306a/krpc-0.3.10.zip#sha256=adb9c50fbbcebe8d2a0e53a6e40ea117fa643aca75b9966be51b65fc4ce45f03 (from https://pypi.org/simple/krpc/), version: 0.3.10
  Found link https://files.pythonhosted.org/packages/63/56/602dc5502e119bdf0ef9e525c785e0ea68670e9365d6baffa1aef556c68c/krpc-0.3.11.zip#sha256=ce3dc121d629103ad699115fac9b6ac8342d4de4c0355534067325c14286a76c (from https://pypi.org/simple/krpc/), version: 0.3.11
  Found link https://files.pythonhosted.org/packages/58/8b/82fd97e0a67b0bcc01708ec1e41cfbf13e8aef62e3ea586b076839b3ed62/krpc-0.4.0.zip#sha256=1dac5fcfc916da53e9692dc8e4d72d622b911ba92f871f1cf42a28c21701ed43 (from https://pypi.org/simple/krpc/), version: 0.4.0
  Found link https://files.pythonhosted.org/packages/41/c5/07753f2c896e02f610f0b514c10268e728587305a4d33b8369e24c0d8d9a/krpc-0.4.1.zip#sha256=85703aef17ce1adbc03196d68dd52182c886e06c1a62d32c2185c1019ef102f0 (from https://pypi.org/simple/krpc/), version: 0.4.1
  Found link https://files.pythonhosted.org/packages/d4/4a/df36c383941e2822aa94ff68d9521762465a5d66dbcb71b3291d1c1ad4ef/krpc-0.4.2.zip#sha256=2374e5be306dd7a2927279be10c4dc22b25bbf2529415a94d731a225713046c7 (from https://pypi.org/simple/krpc/), version: 0.4.2
  Found link https://files.pythonhosted.org/packages/3d/88/753a64ed53759d844352db94d1157730809dfe934feb16da491653859fcf/krpc-0.4.3.zip#sha256=456014dbf5dffc24da2a2651683264e2c0f142b35a2819939d37c165f249013e (from https://pypi.org/simple/krpc/), version: 0.4.3
  Found link https://files.pythonhosted.org/packages/42/ff/7feae7cb34d44f1834828a3febb33b40e196ad804ac0190a0baf52a90dad/krpc-0.4.4.zip#sha256=925dab75053e6c5cf44402ba77a4986d46c14ed8a18769a1ce567ecab67d60bf (from https://pypi.org/simple/krpc/), version: 0.4.4
  Found link https://files.pythonhosted.org/packages/62/53/587a80f67d95e066dc96f53c50f53d31995f0351876c37e1eeadf9bbe1b0/krpc-0.4.4.post1.zip#sha256=61947bf3b7da5887f0eb2b3fa26d68f2e2db417fd91a68c8219365fcf707b4a0 (from https://pypi.org/simple/krpc/), version: 0.4.4.post1
  Found link https://files.pythonhosted.org/packages/47/3c/d03c601148aeb77f88431d9751bada344d60fdbfc65e226756028f0ad4fc/krpc-0.4.5.zip#sha256=00eb17b1faaf437ddae64bb684202ec3c3f632025ee3d6c9faf69c5cec328cf2 (from https://pypi.org/simple/krpc/), version: 0.4.5
  Found link https://files.pythonhosted.org/packages/eb/75/773436079ec9cc134612d8cc5059ef214bff57f96a774f89dd34aa5eb49e/krpc-0.4.6.zip#sha256=94b9383070744a10fd1a347013d6a600569c7c9a52af5429d84a1226878d23a2 (from https://pypi.org/simple/krpc/), version: 0.4.6
  Found link https://files.pythonhosted.org/packages/62/f4/ac40de1186b635f905747d8a35b410a59a3299d11a2bae283ecbd8d0f6b5/krpc-0.4.7.zip#sha256=54e5e8a5e830ff51e30bcdd8881d23acb3b7ee53ebef3cc1d1cf1ea5bbaab786 (from https://pypi.org/simple/krpc/), version: 0.4.7
  Found link https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip#sha256=a5681560e50c90de2a2834ae35ce095b4aa00f4fc44ad7bb8ff03016df8d305c (from https://pypi.org/simple/krpc/), version: 0.4.8
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Given no hashes to check 55 links for project 'krpc': discarding no candidates
Using version 0.4.8 (newest of versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.2.0, 0.2.0.post1, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.8.post1, 0.3.9, 0.3.9.post1, 0.3.10, 0.3.11, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.4.post1, 0.4.5, 0.4.6, 0.4.7, 0.4.8)
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting krpc
  Created temporary directory: D:\Temp\pip-unpack-fjq2ipg8
  Looking up "https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip" in the cache
  Current age based on date: 358931
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 358931
  Using cached https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip
  Added krpc from https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip#sha256=a5681560e50c90de2a2834ae35ce095b4aa00f4fc44ad7bb8ff03016df8d305c to build tracker 'D:\\Temp\\pip-req-tracker-1m01zpl7'
    Running setup.py (path:D:\Temp\pip-install-bli3zvtb\krpc\setup.py) egg_info for package krpc
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\programy\python\lib\site-packages\setuptools\__init__.py", line 18, in <module>
        import setuptools.version
      File "d:\programy\python\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "d:\programy\python\lib\site-packages\pkg_resources\__init__.py", line 80, in <module>
        from pkg_resources.extern import appdirs
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
      File "d:\programy\python\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
        __import__(extant)
      File "d:\programy\python\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
        import win32com.shell
    ValueError: source code string cannot contain null bytes
Cleaning up...
  Removing source in D:\Temp\pip-install-bli3zvtb\krpc
Removed krpc from https://files.pythonhosted.org/packages/b3/21/a2040aac284c04221acb31942d2f78281ce0b01a184762b0e9548803ac60/krpc-0.4.8.zip#sha256=a5681560e50c90de2a2834ae35ce095b4aa00f4fc44ad7bb8ff03016df8d305c from build tracker 'D:\\Temp\\pip-req-tracker-1m01zpl7'
Removed build tracker 'D:\\Temp\\pip-req-tracker-1m01zpl7'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "d:\programy\python\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "d:\programy\python\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "d:\programy\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "d:\programy\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "d:\programy\python\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "d:\programy\python\lib\site-packages\pip\_internal\operations\prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "d:\programy\python\lib\site-packages\pip\_internal\operations\prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "d:\programy\python\lib\site-packages\pip\_internal\distributions\source\legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "d:\programy\python\lib\site-packages\pip\_internal\req\req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "d:\programy\python\lib\site-packages\pip\_internal\operations\generate_metadata.py", line 124, in _generate_metadata_legacy
    command_desc='python setup.py egg_info',
  File "d:\programy\python\lib\site-packages\pip\_internal\utils\subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by JoshGutman** [comment]
Looks like something wrong with your `setuptools`, not this module.  You could try to reinstall `setuptools`:

```
pip install --upgrade --force-reinstall setuptools
```

Or, you could just try to remove the null byte from that file and see if that fixes it, but that seems a little iffy

**Comment by djungelorm** [comment]
Closing as doesn't appear to a bug with kRPC.
