### ISSUE TITLE
krpc-servicedefs raised an exception in KSP 1.9

### ISSUE THREAD

**Issue by Genhis** [krpc/krpc#572]
Command:
```
krpc-servicedefs "C:/Steam/steamapps/common/Kerbal Space Program" MechJeb KRPC.MechJeb.dll KRPC.SpaceCenter.dll -o KRPC.MechJeb.json
```

Exception:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at KRPC.Service.ClassMethodHandler..ctor(Type classType, MethodInfo methodInfo, Boolean returnIsNullable)
   at KRPC.Service.Scanner.ServiceSignature.AddClassPropertyMethod(String cls, Type classType, PropertyInfo property, MethodInfo method, Boolean nullable)
   at KRPC.Service.Scanner.ServiceSignature.AddClassProperty(String cls, Type classType, PropertyInfo property)
   at KRPC.Service.Scanner.Scanner.GetServices(IList`1 errors)
   at ServiceDefinitions.MainClass.Main(String[] args)\n"
```

KSP v1.9
krpctools v0.4.8

Related issue: #523

**Comment by Genhis** [comment]
Works fine in version 0.5.1.
