### ISSUE TITLE
[Python] error module itertools has no attribute izip

### ISSUE THREAD

**Issue by thiagodegan** [krpc/krpc#643]
Hello, I'm trying to use the python client, but it's giving an error in the example "Hello Word".

``` bash
thiagodegan@MacBook-Pro-de-Thiago ~ % python
Python 3.9.1 (default, Dec 29 2020, 09:45:39) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
>>> conn = krpc.connect(name='Hello World')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/krpc/__init__.py", line 50, in connect
    return Client(rpc_connection, stream_connection)
  File "/usr/local/lib/python3.9/site-packages/krpc/client.py", line 33, in __init__
    services = self._invoke('KRPC', 'GetServices', [], [], [],
  File "/usr/local/lib/python3.9/site-packages/krpc/client.py", line 147, in _invoke
    call = self._build_call(service, procedure, args,
  File "/usr/local/lib/python3.9/site-packages/krpc/client.py", line 182, in _build_call
    for i, (value, typ) in enumerate(itertools.izip(args, param_types)):
AttributeError: module 'itertools' has no attribute 'izip'
>>> 
```

**Comment by djungelorm** [comment]
A fix for this will be released in the next few days.

In the meantime you might be able to work around this by modifying `/usr/local/lib/python3.9/site-packages/krpc/client.py` line 182, replacing `itertools.izip` with just `zip`
